### ISSUE TITLE
Remove the number of poses left

### ISSUE THREAD

**Issue by ThomasGaudermen** [AkashBorakay/TennisApp-Kotlin-Test#10]
As we can see on the pictures below, currently, we ask how many services left on the customer app. Or we need to remove this function for the customer application and consider it’s a new forfeit or the customer will be able to add himself a 16 poses forfait to avoid to pay. 
![Screenshot_20230725-220647_TennisPro Customer](https://github.com/AkashBorakay/TennisAppTest/assets/82943755/8c1b5528-0691-492d-a45d-255129e3a17d)

**Comment by kapil-bcssarl** [comment]
Issue resolved
