### ISSUE TITLE
Create reel from backend

### ISSUE THREAD

**Issue by ThomasGaudermen** [AkashBorakay/TennisApp-Kotlin-Test#11]
I create a reel from backend 1 time, and immediately I create another one, each time, I select “display as last order” and then I have 2 reel as “display as last order” as you can see on the pictures below:
![Screenshot_20230727-183450_TennisPro Admin](https://github.com/AkashBorakay/TennisAppTest/assets/82943755/3e96e9eb-9f85-4243-a7f0-a0ca6ff7590d)

**Comment by kapil-bcssarl** [comment]
Issue resolved
