### ISSUE TITLE
Number of poses left v2

### ISSUE THREAD

**Issue by ThomasGaudermen** [AkashBorakay/TennisApp-Kotlin-Test#12]
Be careful, we ask again the number of poses left on reel on customers application when we selected 1 pose 
![Screenshot_20230727-143508_TennisPro Customer](https://github.com/AkashBorakay/TennisAppTest/assets/82943755/0a253e83-c8d6-4c30-be55-c0f21ca87d0d)
![Screenshot_20230727-143511_TennisPro Customer](https://github.com/AkashBorakay/TennisAppTest/assets/82943755/8ec9d315-2645-4421-88ac-06779c5c4343)
![Screenshot_20230727-143514_TennisPro Customer](https://github.com/AkashBorakay/TennisAppTest/assets/82943755/898037c3-88bc-4aab-a9e0-199ecc94353b)

**Comment by kapil-bcssarl** [comment]
Issue resolved
