### ISSUE TITLE
Phone numbre

### ISSUE THREAD

**Issue by ThomasGaudermen** [AkashBorakay/TennisApp-Kotlin-Test#15]
![image](https://github.com/AkashBorakay/TennisAppTest/assets/82943755/10463aff-742a-4672-a17e-5a9e994373c2)

When filling in the phone number, the first number must be alone, because the +33 replace the 0 we have in France.
Can you remove the country code +33 by a country as FR for France. Then, we will provide the mobile number under format 06 XX XX XX XX or 07 XX XX XX XX

**Comment by kapil-bcssarl** [comment]
Done
