### ISSUE TITLE
Information deleted

### ISSUE THREAD

**Issue by ThomasGaudermen** [AkashBorakay/TennisApp-Kotlin-Test#17]
When I fill in the information about the string and I change my answer to “Codage perso” or “Bobine en magasin” afterwards, all the information I provided are deleted.

a video : https://teams.microsoft.com/l/message/48:notes/1688416010709?context=%7B%22contextType%22%3A%22chat%22%7D

**Comment by kapil-bcssarl** [comment]
This was an update. It's implemented.
