### ISSUE TITLE
wording e-mail

### ISSUE THREAD

**Issue by ThomasGaudermen** [AkashBorakay/TennisApp-Kotlin-Test#18]
replace by :
« Nous attirons votre attention sur le fait que la bobine que vous possédez dans notre magasin arrive très prochainement à son terme. Si vous souhaitez commander votre prochaine bobine, merci de nous le faire savoir en nous contactant au 01 46 21 69 69 ou par mail à app.tennispro@gmail.com.

![image](https://github.com/AkashBorakay/TennisAppTest/assets/82943755/dd51dc3e-0083-4129-a266-16d988ef2fc4)

**Comment by kapil-bcssarl** [comment]
Wording updated.
