### ISSUE TITLE
Creation customer without qr-code

### ISSUE THREAD

**Issue by ThomasGaudermen** [AkashBorakay/TennisApp-Kotlin-Test#2]
as you can see on this video, i can't create customer without qr-code :https://borakay.sharepoint.com/sites/TennisPro/_layouts/15/stream.aspx?id=%2Fsites%2FTennisPro%2FShared%20Documents%2FATP%2FOld%20test%2Ftga%20testing%2026mai23%2F2023%5F05%5F30%5F09%5F51%5F25%2Emp4

**Comment by kapil-bcssarl** [comment]
The number format was updated again to the previous hence it was still validating with 9 characters.
