### ISSUE TITLE
Option for e-mail

### ISSUE THREAD

**Issue by ThomasGaudermen** [AkashBorakay/TennisApp-Kotlin-Test#21]
![Screenshot_20230824-152954_Photos](https://github.com/AkashBorakay/TennisAppTest/assets/82943755/ed1ddae4-620e-4d4b-ad30-035d6a6bbb6e)

They are to many options availables for sending e-mail

**Comment by kapil-bcssarl** [comment]
The condition weren't removed for sending mail and completing the order.
