### ISSUE TITLE
Can't select stringer

### ISSUE THREAD

**Issue by ThomasGaudermen** [AkashBorakay/TennisApp-Kotlin-Test#27]
![Screenshot_20230726-222904_TennisPro Admin](https://github.com/AkashBorakay/TennisAppTest/assets/82943755/6cfc4db1-88a3-4275-a281-2fe6e0aa5a26)

I can't select a stringer

**Comment by kapil-bcssarl** [comment]
There was an API update, where some parameters needed to be added from application's end.
