### ISSUE TITLE
Can't create customer

### ISSUE THREAD

**Issue by ThomasGaudermen** [AkashBorakay/TennisApp-Kotlin-Test#28]
![Screenshot_20230725-163951_TennisPro Admin](https://github.com/AkashBorakay/TennisAppTest/assets/82943755/de7ac4b5-a826-455a-9cfb-1090dd342811)

as you can see, i can't create any customer

**Comment by kapil-bcssarl** [comment]
The application wasn't able to create customer as there was an API update from Akash's end.
