### ISSUE TITLE
I can't open the app

### ISSUE THREAD

**Issue by ThomasGaudermen** [AkashBorakay/TennisApp-Kotlin-Test#34]
https://github.com/AkashBorakay/TennisAppTest/assets/82943755/ab5136f9-7fcb-4f64-b9d8-b92f2fe9c98a

When i want to open the app, it's loading indefinitely

**Comment by kapil-bcssarl** [comment]
This was due to the time and date setting which was causing the application to not open it. For a proper connectivity the date and time should be synced.
