### ISSUE TITLE
Champions

### ISSUE THREAD

**Issue by ThomasGaudermen** [AkashBorakay/TennisApp-Kotlin-Test#46]
I can't place any order with champions, when i do the order, i'm blocked at the last screen

**Comment by kapil-bcssarl** [comment]
Can you please provide more information to this as I am able to place and complete the order successfully.

**Comment by ThomasGaudermen** [comment]
No, i just place an order with an existing customers and once it's done, i'm blocked on the last screen, we can have a call when you are available

**Comment by ThomasGaudermen** [comment]
![Screenshot_20230830-144249_TennisPro Admin](https://github.com/AkashBorakay/TennisAppTest/assets/82943755/22c1463f-00d9-4ff3-9233-e7ed276c1e41)
you can see here the screen where i'm blocked
