### ISSUE TITLE
Delivery date

### ISSUE THREAD

**Issue by ThomasGaudermen** [AkashBorakay/TennisApp-Kotlin-Test#5]
![Screenshot_20230605-111109_TennisPro Customer](https://github.com/AkashBorakay/TennisAppTest/assets/82943755/bf1fd356-1252-4b5c-b925-b7a27c7ed2f5)

As you can see, the delivery date are all delay by 2 days

**Comment by kapil-bcssarl** [comment]
This bug was before the latest deployment on the shop. Additionally it was resolved either way.
