### ISSUE TITLE
E-mail title

### ISSUE THREAD

**Issue by ThomasGaudermen** [AkashBorakay/TennisApp-Kotlin-Test#58]
please when a reel is over, replace the e-mail title from : "Votre raquette est cordée 🎾 et votre bobine arrive prochainement à son terme" to "Votre bobine arrive prochainement à son terme et votre raquette est cordée 🎾"

**Comment by AkashBorakay** [comment]
@ThomasGaudermen Can you please check this again and let me know.
Even please close it if it is finished
